import { CurrencyPipe } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-product-list',
  imports: [RouterModule, FormsModule, CurrencyPipe],
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.scss',
})
export class ProductListComponent {
  products: any[] = []; // Tous les produits
  filteredProducts: any[] = []; // Produits filtrés
  categories: any[] = []; // Toutes les catégories
  selectedCategory: string = ''; // Catégorie sélectionnée
  promotedProducts: any[] = []; // Produits en promotion

  constructor(private router: Router) {}

  ngOnInit() {
    // Charger les produits et les catégories
    this.products = this.getProducts();
    this.categories = this.getCategories();
    this.filteredProducts = this.products; // Afficher tous les produits par défaut
    this.promotedProducts = this.getPromotedProducts(); // Charger les produits en promotion
  }

  // Données mockées pour les produits
  getProducts() {
    return [
      {
        id: 1,
        name: 'Jack Daniels',
        image: '/bouteille/jack_daniels.png',
        link: '/bouteille/jack-daniels',
        price: 27.99,
        description: 'Whisky Jack Daniels Old No. 7 70cl, icône du Tennessee.',
        categoryId: 1, // Whisky
        promotion: true,
        discountPercentage: 10,
        volume: '70cl', // Volume de la bouteille
        stock: 50,
        rating: 4.5,
        reviews: 120,
        brand: 'Jack Daniels',
        sku: 'JD12345',
        tags: ['whisky', 'alcool', 'premium'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 700,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2023-10-01',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 5,
          carbohydrates: 15,
          protein: 2,
        },
        allergens: ['gluten'],
        relatedProducts: [2, 5, 7],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 2,
        name: 'Ruinart Brut',
        image: '/bouteille/ruinart_brut.png',
        link: '/bouteille/ruinart-brut',
        price: 45.99,
        description:
          'Bouteille de champagne Ruinart Brut 75cl, élégance et finesse.',
        categoryId: 3, // Champagne
        promotion: false,
        volume: '75cl', // Volume de la bouteille
        stock: 30,
        rating: 4.8,
        reviews: 80,
        brand: 'Ruinart',
        sku: 'RB12345',
        tags: ['champagne', 'luxe', 'élégant'],
        availableSizes: ['75cl', '1.5L'],
        weight: 800,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2022-05-15',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 90,
          fat: 0,
          carbohydrates: 10,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [3, 6, 9],
        isFeatured: false,
        isNew: true,
      },
      {
        id: 3,
        name: 'Moët & Chandon Ice',
        image: '/bouteille/moet_chandon_ice_imperial.jpg',
        link: '/bouteille/moet-chandon-ice-imperial',
        price: 49.99,
        description:
          'Bouteille de champagne Moët & Chandon Ice Impérial 75cl, à déguster sur glace.',
        categoryId: 3, // Champagne
        promotion: true,
        discountPercentage: 15,
        volume: '75cl', // Volume de la bouteille
        stock: 45,
        rating: 4.7,
        reviews: 150,
        brand: 'Moët & Chandon',
        sku: 'MCI12345',
        tags: ['champagne', 'été', 'glace'],
        availableSizes: ['75cl', '1.5L'],
        weight: 850,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-06-20',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 95,
          fat: 0,
          carbohydrates: 11,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [2, 5, 8],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 4,
        name: 'Absolut',
        image: '/bouteille/absolut_70cl.jpg',
        link: '/bouteille/absolut',
        price: 19.99,
        description: 'Bouteille de vodka Absolut 70cl, pure et authentique.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 60,
        rating: 4.3,
        reviews: 200,
        brand: 'Absolut',
        sku: 'AB12345',
        tags: ['vodka', 'pure', 'authentique'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2020-01-10',
        expirationDate: '2024-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [6, 9, 12],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 5,
        name: 'Desperados Red',
        image: '/bouteille/desperados_red_33cl.jpg',
        link: '/bouteille/desperados-red',
        price: 2.49,
        description:
          'Bière Desperados Red 33cl, saveur unique avec une touche fruitée.',
        categoryId: 5, // Bière
        promotion: true,
        discountPercentage: 20,
        volume: '33cl', // Volume de la bouteille
        stock: 100,
        rating: 4.1,
        reviews: 180,
        brand: 'Desperados',
        sku: 'DR12345',
        tags: ['bière', 'fruitée', 'été'],
        availableSizes: ['33cl', '50cl'],
        weight: 350,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'red',
        material: 'glass',
        releaseDate: '2022-03-15',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 12,
          protein: 1,
        },
        allergens: ['gluten'],
        relatedProducts: [7, 10, 13],
        isFeatured: false,
        isNew: true,
      },
      {
        id: 6,
        name: 'Belvedere Magnum',
        image: '/bouteille/belvedere_magnum.jpg',
        link: '/bouteille/belvedere-magnum',
        price: 79.99,
        description:
          'Vodka Belvedere en format Magnum 1,75L, idéale pour les grandes occasions.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '1.75L', // Volume de la bouteille
        stock: 20,
        rating: 4.6,
        reviews: 90,
        brand: 'Belvedere',
        sku: 'BM12345',
        tags: ['vodka', 'magnum', 'luxe'],
        availableSizes: ['70cl', '1L', '1.75L'],
        weight: 1750,
        dimensions: { width: 15, height: 30, depth: 15 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2021-11-25',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [8, 11, 14],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 7,
        name: 'Belvedere',
        image: '/bouteille/belvedere_70cl.jpg',
        link: '/bouteille/belvedere',
        price: 39.99,
        description: 'Vodka Belvedere 70cl, une référence de qualité premium.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 40,
        rating: 4.4,
        reviews: 120,
        brand: 'Belvedere',
        sku: 'BE12345',
        tags: ['vodka', 'premium', 'qualité'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2020-09-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [9, 12, 15],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 8,
        name: 'Chivas Regal',
        image: '/bouteille/chivas_1l.jpg',
        link: '/bouteille/chivas',
        price: 34.99,
        description:
          'Whisky Chivas Regal 12 ans 1L, un classique équilibré et riche.',
        categoryId: 1, // Whisky
        promotion: true,
        discountPercentage: 12,
        volume: '1L', // Volume de la bouteille
        stock: 35,
        rating: 4.5,
        reviews: 130,
        brand: 'Chivas Regal',
        sku: 'CR12345',
        tags: ['whisky', 'classique', 'équilibré'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 1000,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2019-08-20',
        expirationDate: '2024-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [10, 13, 16],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 9,
        name: 'Grey Goose',
        image: '/bouteille/grey_goose.jpg',
        link: '/bouteille/grey-goose',
        price: 44.99,
        description:
          'Vodka Grey Goose 70cl, reconnue pour sa douceur exceptionnelle.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 50,
        rating: 4.7,
        reviews: 160,
        brand: 'Grey Goose',
        sku: 'GG12345',
        tags: ['vodka', 'douceur', 'premium'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2021-07-15',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [11, 14, 17],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 10,
        name: "Jus d'ananas",
        image: '/bouteille/jus_ananas.jpg',
        link: '/bouteille/jus-ananas',
        price: 4.99,
        description: "Bouteille de jus d'ananas 1L, fraîche et naturelle.",
        categoryId: 6, // Jus
        promotion: false,
        volume: '1L', // Volume de la bouteille
        stock: 80,
        rating: 4.2,
        reviews: 110,
        brand: 'Tropicana',
        sku: 'JA12345',
        tags: ['jus', 'fruité', 'naturel'],
        availableSizes: ['1L', '2L'],
        weight: 1000,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'yellow',
        material: 'plastic',
        releaseDate: '2022-04-25',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 110,
          fat: 0,
          carbohydrates: 25,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [12, 15, 18],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 11,
        name: 'Cristaline',
        image: '/bouteille/cristaline_50cl.jpg',
        link: '/bouteille/cristaline-50cl',
        price: 1.99,
        description:
          "Bouteille d'eau Cristaline 50cl, pure et rafraîchissante.",
        categoryId: 6, // Jus
        promotion: false,
        volume: '50cl', // Volume de la bouteille
        stock: 100,
        rating: 4.3,
        reviews: 140,
        brand: 'Cristaline',
        sku: 'CR12345',
        tags: ['eau', 'pure', 'rafraîchissante'],
        availableSizes: ['50cl', '1L', '1.5L'],
        weight: 500,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'clear',
        material: 'plastic',
        releaseDate: '2020-06-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 0,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [13, 16, 19],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 12,
        name: 'Coca-Cola',
        image: '/bouteille/coca.jpg',
        link: '/bouteille/coca',
        price: 2.49,
        description:
          'Bouteille de Coca-Cola 1,5L, la boisson gazeuse classique.',
        categoryId: 6, // Jus
        promotion: true,
        discountPercentage: 10,
        volume: '1.5L', // Volume de la bouteille
        stock: 90,
        rating: 4.4,
        reviews: 170,
        brand: 'Coca-Cola',
        sku: 'CC12345',
        tags: ['soda', 'classique', 'gazeuse'],
        availableSizes: ['1.5L', '2L'],
        weight: 1500,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'brown',
        material: 'plastic',
        releaseDate: '2021-05-20',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 39,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [14, 17, 20],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 13,
        name: 'Desperados',
        image: '/bouteille/desperados_red_33cl.jpg',
        link: '/bouteille/desperados',
        price: 2.99,
        description:
          'Bière Desperados 33cl, une fusion unique de bière et de tequila.',
        categoryId: 5, // Bière
        promotion: false,
        volume: '33cl', // Volume de la bouteille
        stock: 120,
        rating: 4.1,
        reviews: 190,
        brand: 'Desperados',
        sku: 'DE12345',
        tags: ['bière', 'tequila', 'fusion'],
        availableSizes: ['33cl', '50cl'],
        weight: 350,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2022-03-15',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 12,
          protein: 1,
        },
        allergens: ['gluten'],
        relatedProducts: [15, 18, 21],
        isFeatured: false,
        isNew: true,
      },
      {
        id: 14,
        name: 'Eristoff',
        image: '/bouteille/freixenet.jpg', // A CHANGER
        link: '/bouteille/eristoff',
        price: 18.99,
        description: 'Vodka Eristoff 70cl, une vodka douce et aromatique.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 60,
        rating: 4.3,
        reviews: 120,
        brand: 'Eristoff',
        sku: 'ER12345',
        tags: ['vodka', 'douce', 'aromatique'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2020-09-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [16, 19, 22],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 15,
        name: 'Freixenet',
        image: '/bouteille/freixenet.jpg',
        link: '/bouteille/freixenet',
        price: 12.99,
        description:
          'Bouteille de cava Freixenet 75cl, un vin pétillant espagnol.',
        categoryId: 3, // Champagne
        promotion: true,
        discountPercentage: 15,
        volume: '75cl', // Volume de la bouteille
        stock: 45,
        rating: 4.6,
        reviews: 130,
        brand: 'Freixenet',
        sku: 'FR12345',
        tags: ['cava', 'pétillant', 'espagnol'],
        availableSizes: ['75cl', '1.5L'],
        weight: 800,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-06-20',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 90,
          fat: 0,
          carbohydrates: 10,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [17, 20, 23],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 16,
        name: "Grant's",
        image: '/bouteille/jack_daniels.png',
        link: '/bouteille/grants',
        price: 22.99,
        description: "Whisky Grant's 70cl, un blended whisky écossais.",
        categoryId: 1, // Whisky
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 50,
        rating: 4.4,
        reviews: 110,
        brand: "Grant's",
        sku: 'GR12345',
        tags: ['whisky', 'blended', 'écossais'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2020-08-15',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [18, 21, 24],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 17,
        name: 'Grey Goose Magnum',
        image: '/bouteille/grey-goose magnum 40 150CL 110€.jpg', // A CHANGER
        link: '/bouteille/grey-goose-magnum',
        price: 110.0,
        description:
          'Vodka Grey Goose Magnum 1,5L, idéale pour les grandes fêtes.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '1.5L', // Volume de la bouteille
        stock: 20,
        rating: 4.7,
        reviews: 150,
        brand: 'Grey Goose',
        sku: 'GGM12345',
        tags: ['vodka', 'magnum', 'fête'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 1500,
        dimensions: { width: 15, height: 30, depth: 15 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2021-11-25',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [19, 22, 25],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 18,
        name: 'Heineken',
        image: '/bouteille/heineken_25cl.jpg',
        link: '/bouteille/heineken',
        price: 1.99,
        description:
          'Bière Heineken 25cl, une lager néerlandaise rafraîchissante.',
        categoryId: 5, // Bière
        promotion: false,
        volume: '25cl', // Volume de la bouteille
        stock: 150,
        rating: 4.2,
        reviews: 180,
        brand: 'Heineken',
        sku: 'HE12345',
        tags: ['bière', 'lager', 'néerlandaise'],
        availableSizes: ['25cl', '33cl', '50cl'],
        weight: 250,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'green',
        material: 'glass',
        releaseDate: '2022-04-25',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 12,
          protein: 1,
        },
        allergens: ['gluten'],
        relatedProducts: [20, 23, 26],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 19,
        name: 'Jack Daniels Honey',
        image: '/bouteille/jack_daniels.png',
        link: '/bouteille/jack-daniels-honey',
        price: 29.99,
        description:
          'Whisky Jack Daniels Honey 70cl, une touche de miel pour plus de douceur.',
        categoryId: 1, // Whisky
        promotion: true,
        discountPercentage: 10,
        volume: '70cl', // Volume de la bouteille
        stock: 40,
        rating: 4.5,
        reviews: 160,
        brand: 'Jack Daniels',
        sku: 'JDH12345',
        tags: ['whisky', 'miel', 'douceur'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-07-15',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [21, 24, 27],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 20,
        name: 'Damoiseau Cubis',
        image: '/bouteille/damoiseau_cubis.webp',
        link: '/bouteille/damoiseau-cubis',
        price: 24.99,
        description: 'Rhum Damoiseau Cubis 1L, un rhum agricole de Guadeloupe.',
        categoryId: 7, // Rhum
        promotion: false,
        volume: '1L', // Volume de la bouteille
        stock: 30,
        rating: 4.6,
        reviews: 110,
        brand: 'Damoiseau',
        sku: 'DC12345',
        tags: ['rhum', 'agricole', 'guadeloupe'],
        availableSizes: ['70cl', '1L'],
        weight: 1000,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2020-09-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [22, 25, 28],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 21,
        name: 'Saint James',
        image: '/bouteille/saint_james.webp',
        link: '/bouteille/saint-james',
        price: 19.99,
        description: 'Rhum Saint James 70cl, un rhum agricole de Martinique.',
        categoryId: 7, // Rhum
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 45,
        rating: 4.4,
        reviews: 130,
        brand: 'Saint James',
        sku: 'SJ12345',
        tags: ['rhum', 'agricole', 'martinique'],
        availableSizes: ['70cl', '1L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-06-20',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [23, 26, 29],
        isFeatured: false,
        isNew: false,
      },
    ];
  }

  // Données mockées pour les catégories
  getCategories() {
    return [
      {
        id: 1,
        name: 'Whisky',
        image: '/categorie/whisky.webp',
        link: '/whisky',
      },
      { id: 2, name: 'Vodka', image: '/categorie/vodka.webp', link: '/vodka' },
      {
        id: 3,
        name: 'Champagne',
        image: '/categorie/champagne.webp',
        link: '/champagne',
      },
      { id: 4, name: 'Vin', image: '/categorie/vin.jpg', link: '/vin' },
      { id: 5, name: 'Bière', image: '/categorie/biere.jpg', link: '/biere' },
      { id: 6, name: 'Jus', image: '/categorie/jus.jpg', link: '/jus' },
    ];
  }

  // Filtrer les produits par catégorie
  filterProducts() {
    if (this.selectedCategory) {
      this.filteredProducts = this.products.filter(
        (product) => product.categoryId === +this.selectedCategory
      );
    } else {
      this.filteredProducts = this.products; // Afficher tous les produits si aucune catégorie n'est sélectionnée
    }
  }

  // Obtenir les produits en promotion
  getPromotedProducts() {
    return this.products.filter((product) => product.promotion);
  }

  // Naviguer vers la page de détail du produit
  navigateToProduct(product: any) {
    this.router.navigate([product.link]);
  }
}
