import { CurrencyPipe } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-product-list',
  imports: [RouterModule, FormsModule, CurrencyPipe],
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.scss',
})
export class ProductListComponent {
  products: any[] = []; // Tous les produits
  filteredProducts: any[] = []; // Produits filtrés
  categories: any[] = []; // Toutes les catégories
  selectedCategory: string = ''; // Catégorie sélectionnée
  promotedProducts: any[] = []; // Produits en promotion

  constructor(private router: Router) {}

  ngOnInit() {
    // Charger les produits et les catégories
    this.products = this.getProducts();
    this.categories = this.getCategories();
    this.filteredProducts = this.products; // Afficher tous les produits par défaut
    this.promotedProducts = this.getPromotedProducts(); // Charger les produits en promotion
  }

  // Données mockées pour les produits
  getProducts() {
    return [
      {
        id: 1,
        name: 'Jack Daniels',
        image: '/bouteille/jack_daniels.png',
        link: '/bouteille/jack-daniels',
        price: 27.99,
        description: 'Whisky Jack Daniels Old No. 7 70cl, icône du Tennessee.',
        categoryId: 1, // Whisky
        promotion: true,
        discountPercentage: 10,
        volume: '70cl', // Volume de la bouteille
        stock: 50,
        rating: 4.5,
        reviews: 120,
        brand: 'Jack Daniels',
        sku: 'JD12345',
        tags: ['whisky', 'alcool', 'premium'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 700,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2023-10-01',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 5,
          carbohydrates: 15,
          protein: 2,
        },
        allergens: ['gluten'],
        relatedProducts: [2, 5, 7],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 2,
        name: 'Ruinart Brut',
        image: '/bouteille/ruinart_brut.png',
        link: '/bouteille/ruinart-brut',
        price: 45.99,
        description:
          'Bouteille de champagne Ruinart Brut 75cl, élégance et finesse.',
        categoryId: 3, // Champagne
        promotion: false,
        volume: '75cl', // Volume de la bouteille
        stock: 30,
        rating: 4.8,
        reviews: 80,
        brand: 'Ruinart',
        sku: 'RB12345',
        tags: ['champagne', 'luxe', 'élégant'],
        availableSizes: ['75cl', '1.5L'],
        weight: 800,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2022-05-15',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 90,
          fat: 0,
          carbohydrates: 10,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [3, 6, 9],
        isFeatured: false,
        isNew: true,
      },
      {
        id: 3,
        name: 'Moët & Chandon Ice',
        image: '/bouteille/moet_chandon_ice_imperial.jpg',
        link: '/bouteille/moet-chandon-ice-imperial',
        price: 49.99,
        description:
          'Bouteille de champagne Moët & Chandon Ice Impérial 75cl, à déguster sur glace.',
        categoryId: 3, // Champagne
        promotion: true,
        discountPercentage: 15,
        volume: '75cl', // Volume de la bouteille
        stock: 45,
        rating: 4.7,
        reviews: 150,
        brand: 'Moët & Chandon',
        sku: 'MCI12345',
        tags: ['champagne', 'été', 'glace'],
        availableSizes: ['75cl', '1.5L'],
        weight: 850,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-06-20',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 95,
          fat: 0,
          carbohydrates: 11,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [2, 5, 8],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 4,
        name: 'Absolut',
        image: '/bouteille/absolut_70cl.jpg',
        link: '/bouteille/absolut',
        price: 19.99,
        description: 'Bouteille de vodka Absolut 70cl, pure et authentique.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 60,
        rating: 4.3,
        reviews: 200,
        brand: 'Absolut',
        sku: 'AB12345',
        tags: ['vodka', 'pure', 'authentique'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2020-01-10',
        expirationDate: '2024-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [6, 9, 12],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 5,
        name: 'Desperados Red',
        image: '/bouteille/desperados_red_33cl.jpg',
        link: '/bouteille/desperados-red',
        price: 2.49,
        description:
          'Bière Desperados Red 33cl, saveur unique avec une touche fruitée.',
        categoryId: 5, // Bière
        promotion: true,
        discountPercentage: 20,
        volume: '33cl', // Volume de la bouteille
        stock: 100,
        rating: 4.1,
        reviews: 180,
        brand: 'Desperados',
        sku: 'DR12345',
        tags: ['bière', 'fruitée', 'été'],
        availableSizes: ['33cl', '50cl'],
        weight: 350,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'red',
        material: 'glass',
        releaseDate: '2022-03-15',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 12,
          protein: 1,
        },
        allergens: ['gluten'],
        relatedProducts: [7, 10, 13],
        isFeatured: false,
        isNew: true,
      },
      {
        id: 6,
        name: 'Belvedere Magnum',
        image: '/bouteille/belvedere_magnum.jpg',
        link: '/bouteille/belvedere-magnum',
        price: 79.99,
        description:
          'Vodka Belvedere en format Magnum 1,75L, idéale pour les grandes occasions.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '1.75L', // Volume de la bouteille
        stock: 20,
        rating: 4.6,
        reviews: 90,
        brand: 'Belvedere',
        sku: 'BM12345',
        tags: ['vodka', 'magnum', 'luxe'],
        availableSizes: ['70cl', '1L', '1.75L'],
        weight: 1750,
        dimensions: { width: 15, height: 30, depth: 15 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2021-11-25',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [8, 11, 14],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 7,
        name: 'Belvedere',
        image: '/bouteille/belvedere_70cl.jpg',
        link: '/bouteille/belvedere',
        price: 39.99,
        description: 'Vodka Belvedere 70cl, une référence de qualité premium.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 40,
        rating: 4.4,
        reviews: 120,
        brand: 'Belvedere',
        sku: 'BE12345',
        tags: ['vodka', 'premium', 'qualité'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2020-09-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [9, 12, 15],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 8,
        name: 'Chivas Regal',
        image: '/bouteille/chivas_1l.jpg',
        link: '/bouteille/chivas',
        price: 34.99,
        description:
          'Whisky Chivas Regal 12 ans 1L, un classique équilibré et riche.',
        categoryId: 1, // Whisky
        promotion: true,
        discountPercentage: 12,
        volume: '1L', // Volume de la bouteille
        stock: 35,
        rating: 4.5,
        reviews: 130,
        brand: 'Chivas Regal',
        sku: 'CR12345',
        tags: ['whisky', 'classique', 'équilibré'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 1000,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2019-08-20',
        expirationDate: '2024-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [10, 13, 16],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 9,
        name: 'Grey Goose',
        image: '/bouteille/grey_goose.jpg',
        link: '/bouteille/grey-goose',
        price: 44.99,
        description:
          'Vodka Grey Goose 70cl, reconnue pour sa douceur exceptionnelle.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 50,
        rating: 4.7,
        reviews: 160,
        brand: 'Grey Goose',
        sku: 'GG12345',
        tags: ['vodka', 'douceur', 'premium'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2021-07-15',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [11, 14, 17],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 10,
        name: "Jus d'ananas",
        image: '/bouteille/jus_ananas.jpg',
        link: '/bouteille/jus-ananas',
        price: 4.99,
        description: "Bouteille de jus d'ananas 1L, fraîche et naturelle.",
        categoryId: 6, // Jus
        promotion: false,
        volume: '1L', // Volume de la bouteille
        stock: 80,
        rating: 4.2,
        reviews: 110,
        brand: 'Tropicana',
        sku: 'JA12345',
        tags: ['jus', 'fruité', 'naturel'],
        availableSizes: ['1L', '2L'],
        weight: 1000,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'yellow',
        material: 'plastic',
        releaseDate: '2022-04-25',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 110,
          fat: 0,
          carbohydrates: 25,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [12, 15, 18],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 11,
        name: 'Cristaline',
        image: '/bouteille/cristaline_50cl.jpg',
        link: '/bouteille/cristaline-50cl',
        price: 1.99,
        description:
          "Bouteille d'eau Cristaline 50cl, pure et rafraîchissante.",
        categoryId: 6, // Jus
        promotion: false,
        volume: '50cl', // Volume de la bouteille
        stock: 100,
        rating: 4.3,
        reviews: 140,
        brand: 'Cristaline',
        sku: 'CR12345',
        tags: ['eau', 'pure', 'rafraîchissante'],
        availableSizes: ['50cl', '1L', '1.5L'],
        weight: 500,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'clear',
        material: 'plastic',
        releaseDate: '2020-06-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 0,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [13, 16, 19],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 12,
        name: 'Coca-Cola',
        image: '/bouteille/coca.jpg',
        link: '/bouteille/coca',
        price: 2.49,
        description:
          'Bouteille de Coca-Cola 1,5L, la boisson gazeuse classique.',
        categoryId: 6, // Jus
        promotion: true,
        discountPercentage: 10,
        volume: '1.5L', // Volume de la bouteille
        stock: 90,
        rating: 4.4,
        reviews: 170,
        brand: 'Coca-Cola',
        sku: 'CC12345',
        tags: ['soda', 'classique', 'gazeuse'],
        availableSizes: ['1.5L', '2L'],
        weight: 1500,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'brown',
        material: 'plastic',
        releaseDate: '2021-05-20',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 39,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [14, 17, 20],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 13,
        name: 'Desperados',
        image: '/bouteille/desperados_red_33cl.jpg',
        link: '/bouteille/desperados',
        price: 2.99,
        description:
          'Bière Desperados 33cl, une fusion unique de bière et de tequila.',
        categoryId: 5, // Bière
        promotion: false,
        volume: '33cl', // Volume de la bouteille
        stock: 120,
        rating: 4.1,
        reviews: 190,
        brand: 'Desperados',
        sku: 'DE12345',
        tags: ['bière', 'tequila', 'fusion'],
        availableSizes: ['33cl', '50cl'],
        weight: 350,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2022-03-15',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 12,
          protein: 1,
        },
        allergens: ['gluten'],
        relatedProducts: [15, 18, 21],
        isFeatured: false,
        isNew: true,
      },
      {
        id: 14,
        name: 'Eristoff',
        image: '/bouteille/freixenet.jpg', // A CHANGER
        link: '/bouteille/eristoff',
        price: 18.99,
        description: 'Vodka Eristoff 70cl, une vodka douce et aromatique.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 60,
        rating: 4.3,
        reviews: 120,
        brand: 'Eristoff',
        sku: 'ER12345',
        tags: ['vodka', 'douce', 'aromatique'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2020-09-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [16, 19, 22],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 15,
        name: 'Freixenet',
        image: '/bouteille/freixenet.jpg',
        link: '/bouteille/freixenet',
        price: 12.99,
        description:
          'Bouteille de cava Freixenet 75cl, un vin pétillant espagnol.',
        categoryId: 3, // Champagne
        promotion: true,
        discountPercentage: 15,
        volume: '75cl', // Volume de la bouteille
        stock: 45,
        rating: 4.6,
        reviews: 130,
        brand: 'Freixenet',
        sku: 'FR12345',
        tags: ['cava', 'pétillant', 'espagnol'],
        availableSizes: ['75cl', '1.5L'],
        weight: 800,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-06-20',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 90,
          fat: 0,
          carbohydrates: 10,
          protein: 1,
        },
        allergens: [],
        relatedProducts: [17, 20, 23],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 16,
        name: "Grant's",
        image: '/bouteille/jack_daniels.png',
        link: '/bouteille/grants',
        price: 22.99,
        description: "Whisky Grant's 70cl, un blended whisky écossais.",
        categoryId: 1, // Whisky
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 50,
        rating: 4.4,
        reviews: 110,
        brand: "Grant's",
        sku: 'GR12345',
        tags: ['whisky', 'blended', 'écossais'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2020-08-15',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [18, 21, 24],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 17,
        name: 'Grey Goose Magnum',
        image: '/bouteille/grey-goose magnum 40 150CL 110€.jpg', // A CHANGER
        link: '/bouteille/grey-goose-magnum',
        price: 110.0,
        description:
          'Vodka Grey Goose Magnum 1,5L, idéale pour les grandes fêtes.',
        categoryId: 2, // Vodka
        promotion: false,
        volume: '1.5L', // Volume de la bouteille
        stock: 20,
        rating: 4.7,
        reviews: 150,
        brand: 'Grey Goose',
        sku: 'GGM12345',
        tags: ['vodka', 'magnum', 'fête'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 1500,
        dimensions: { width: 15, height: 30, depth: 15 },
        color: 'clear',
        material: 'glass',
        releaseDate: '2021-11-25',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 64,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [19, 22, 25],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 18,
        name: 'Heineken',
        image: '/bouteille/heineken_25cl.jpg',
        link: '/bouteille/heineken',
        price: 1.99,
        description:
          'Bière Heineken 25cl, une lager néerlandaise rafraîchissante.',
        categoryId: 5, // Bière
        promotion: false,
        volume: '25cl', // Volume de la bouteille
        stock: 150,
        rating: 4.2,
        reviews: 180,
        brand: 'Heineken',
        sku: 'HE12345',
        tags: ['bière', 'lager', 'néerlandaise'],
        availableSizes: ['25cl', '33cl', '50cl'],
        weight: 250,
        dimensions: { width: 8, height: 15, depth: 8 },
        color: 'green',
        material: 'glass',
        releaseDate: '2022-04-25',
        expirationDate: '2023-12-31',
        nutritionFacts: {
          calories: 140,
          fat: 0,
          carbohydrates: 12,
          protein: 1,
        },
        allergens: ['gluten'],
        relatedProducts: [20, 23, 26],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 19,
        name: 'Jack Daniels Honey',
        image: '/bouteille/jack_daniels.png',
        link: '/bouteille/jack-daniels-honey',
        price: 29.99,
        description:
          'Whisky Jack Daniels Honey 70cl, une touche de miel pour plus de douceur.',
        categoryId: 1, // Whisky
        promotion: true,
        discountPercentage: 10,
        volume: '70cl', // Volume de la bouteille
        stock: 40,
        rating: 4.5,
        reviews: 160,
        brand: 'Jack Daniels',
        sku: 'JDH12345',
        tags: ['whisky', 'miel', 'douceur'],
        availableSizes: ['70cl', '1L', '1.5L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-07-15',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [21, 24, 27],
        isFeatured: true,
        isNew: false,
      },
      {
        id: 20,
        name: 'Damoiseau Cubis',
        image: '/bouteille/damoiseau_cubis.webp',
        link: '/bouteille/damoiseau-cubis',
        price: 24.99,
        description: 'Rhum Damoiseau Cubis 1L, un rhum agricole de Guadeloupe.',
        categoryId: 7, // Rhum
        promotion: false,
        volume: '1L', // Volume de la bouteille
        stock: 30,
        rating: 4.6,
        reviews: 110,
        brand: 'Damoiseau',
        sku: 'DC12345',
        tags: ['rhum', 'agricole', 'guadeloupe'],
        availableSizes: ['70cl', '1L'],
        weight: 1000,
        dimensions: { width: 12, height: 25, depth: 12 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2020-09-10',
        expirationDate: '2025-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [22, 25, 28],
        isFeatured: false,
        isNew: false,
      },
      {
        id: 21,
        name: 'Saint James',
        image: '/bouteille/saint_james.webp',
        link: '/bouteille/saint-james',
        price: 19.99,
        description: 'Rhum Saint James 70cl, un rhum agricole de Martinique.',
        categoryId: 7, // Rhum
        promotion: false,
        volume: '70cl', // Volume de la bouteille
        stock: 45,
        rating: 4.4,
        reviews: 130,
        brand: 'Saint James',
        sku: 'SJ12345',
        tags: ['rhum', 'agricole', 'martinique'],
        availableSizes: ['70cl', '1L'],
        weight: 750,
        dimensions: { width: 10, height: 20, depth: 10 },
        color: 'gold',
        material: 'glass',
        releaseDate: '2021-06-20',
        expirationDate: '2026-12-31',
        nutritionFacts: {
          calories: 120,
          fat: 0,
          carbohydrates: 0,
          protein: 0,
        },
        allergens: [],
        relatedProducts: [23, 26, 29],
        isFeatured: false,
        isNew: false,
      },
    ];
  }

  // Données mockées pour les catégories
  getCategories() {
    return [
      {
        id: 1,
        name: 'Whisky',
        image: '/categorie/whisky.webp',
        link: '/whisky',
      },
      { id: 2, name: 'Vodka', image: '/categorie/vodka.webp', link: '/vodka' },
      {
        id: 3,
        name: 'Champagne',
        image: '/categorie/champagne.webp',
        link: '/champagne',
      },
      { id: 4, name: 'Vin', image: '/categorie/vin.jpg', link: '/vin' },
      { id: 5, name: 'Bière', image: '/categorie/biere.jpg', link: '/biere' },
      { id: 6, name: 'Jus', image: '/categorie/jus.jpg', link: '/jus' },
    ];
  }

  // Filtrer les produits par catégorie
  filterProducts() {
    if (this.selectedCategory) {
      this.filteredProducts = this.products.filter(
        (product) => product.categoryId === +this.selectedCategory
      );
    } else {
      this.filteredProducts = this.products; // Afficher tous les produits si aucune catégorie n'est sélectionnée
    }
  }

  // Obtenir les produits en promotion
  getPromotedProducts() {
    return this.products.filter((product) => product.promotion);
  }

  // Naviguer vers la page de détail du produit
  navigateToProduct(product: any) {
    this.router.navigate([product.link]);
  }
}

/** 
[
  {
      "id": 1,
      "name": "Jus d'ananas",
      "image": "/bouteille/jus_ananas.jpg",
      "link": "/bouteille/jus-ananas",
      "price": 2.99,
      "description": "Jus d'ananas en brique, rafraîchissant et naturel.",
      "categoryId": 1, // Jus
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1L",
      "stock": 100,
      "rating": 4.2,
      "reviews": 50,
      "brand": "Marque Ananas",
      "sku": "JA12345",
      "tags": ["jus", "ananas", "boisson"],
      "availableSizes": ["1L", "2L"],
      "weight": 1000,
      "dimensions": { "width": 10, "height": 20, "depth": 5 },
      "color": "yellow",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 50,
          "fat": 0,
          "carbohydrates": 12,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [2, 3],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 2,
      "name": "10 Bouteilles à Champagne",
      "image": "/bouteille/10_BUTEILLES_A_CHAMPAGNE.jpg",
      "link": "/bouteille/10-bouteilles-champagne",
      "price": 19.99,
      "description": "Pack de 10 bouteilles à champagne, parfait pour les événements.",
      "categoryId": 5, // Accessoires
      "promotion": true,
      "discountPercentage": 15,
      "volume": "10x75cl",
      "stock": 50,
      "rating": 4.5,
      "reviews": 30,
      "brand": "Marque Champagne",
      "sku": "BC12345",
      "tags": ["accessoire", "champagne", "événement"],
      "availableSizes": ["10x75cl"],
      "weight": 2000,
      "dimensions": { "width": 30, "height": 30, "depth": 30 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-05-01",
      "expirationDate": "2025-05-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [1, 4],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 3,
      "name": "100 Gobelets 25cl",
      "image": "/bouteille/100_gobelet_25cl.jpg",
      "link": "/bouteille/100-gobelets-25cl",
      "price": 9.99,
      "description": "Pack de 100 gobelets en plastique de 25cl, idéal pour les fêtes.",
      "categoryId": 5, // Accessoires
      "promotion": false,
      "discountPercentage": 0,
      "volume": "100x25cl",
      "stock": 200,
      "rating": 4.0,
      "reviews": 20,
      "brand": "Marque Gobelet",
      "sku": "GG12345",
      "tags": ["accessoire", "gobelet", "fête"],
      "availableSizes": ["100x25cl"],
      "weight": 1000,
      "dimensions": { "width": 20, "height": 20, "depth": 20 },
      "color": "clear",
      "material": "plastic",
      "releaseDate": "2023-03-01",
      "expirationDate": "2025-03-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [2, 4],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 4,
      "name": "Absolut Vodka",
      "image": "/bouteille/absolut.jpg",
      "link": "/bouteille/absolut-vodka",
      "price": 19.99,
      "description": "Vodka Absolut, 70cl, origine suédoise.",
      "categoryId": 2, // Vodka
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 100,
      "rating": 4.2,
      "reviews": 85,
      "brand": "Absolut",
      "sku": "AB12345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2022-05-15",
      "expirationDate": "2024-12-31",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [1, 3, 6],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 5,
      "name": "Bec Verseur",
      "image": "/bouteille/BEC_VERSEUR.jpg",
      "link": "/bouteille/bec-verseur",
      "price": 4.99,
      "description": "Bec verseur pour bouteilles, pratique et réutilisable.",
      "categoryId": 5, // Accessoires
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1 unité",
      "stock": 500,
      "rating": 4.3,
      "reviews": 100,
      "brand": "Marque Verseur",
      "sku": "BV12345",
      "tags": ["accessoire", "verseur", "bouteille"],
      "availableSizes": ["1 unité"],
      "weight": 50,
      "dimensions": { "width": 5, "height": 5, "depth": 5 },
      "color": "clear",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [2, 4],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 6,
      "name": "Belvedere Magnum",
      "image": "/bouteille/belvedere_magnum.jpg",
      "link": "/bouteille/belvedere-magnum",
      "price": 49.99,
      "description": "Bouteille de vodka Belvedere en format magnum, 1.5L.",
      "categoryId": 2, // Vodka
      "promotion": true,
      "discountPercentage": 10,
      "volume": "1.5L",
      "stock": 20,
      "rating": 4.7,
      "reviews": 40,
      "brand": "Belvedere",
      "sku": "BM12345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["1.5L"],
      "weight": 1500,
      "dimensions": { "width": 15, "height": 30, "depth": 15 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-06-01",
      "expirationDate": "2025-06-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [4, 7],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 7,
      "name": "Belvedere",
      "image": "/bouteille/belvedere.jpg",
      "link": "/bouteille/belvedere",
      "price": 29.99,
      "description": "Bouteille de vodka Belvedere, 70cl.",
      "categoryId": 2, // Vodka
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 50,
      "rating": 4.6,
      "reviews": 60,
      "brand": "Belvedere",
      "sku": "BE12345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-07-01",
      "expirationDate": "2025-07-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [4, 6],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 8,
      "name": "Chivas",
      "image": "/bouteille/chivas.jpg",
      "link": "/bouteille/chivas",
      "price": 24.99,
      "description": "Bouteille de whisky Chivas, 70cl.",
      "categoryId": 1, // Whisky
      "promotion": true,
      "discountPercentage": 15,
      "volume": "70cl",
      "stock": 30,
      "rating": 4.4,
      "reviews": 70,
      "brand": "Chivas",
      "sku": "CH12345",
      "tags": ["whisky", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-04-01",
      "expirationDate": "2025-04-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [9, 10],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 9,
      "name": "Coca-Cola",
      "image": "/bouteille/coca.jpg",
      "link": "/bouteille/coca-cola",
      "price": 1.99,
      "description": "Bouteille de Coca-Cola, 33cl.",
      "categoryId": 6, // Boissons gazeuses
      "promotion": false,
      "discountPercentage": 0,
      "volume": "33cl",
      "stock": 200,
      "rating": 4.8,
      "reviews": 150,
      "brand": "Coca-Cola",
      "sku": "CC12345",
      "tags": ["boisson", "gazeuse", "soda"],
      "availableSizes": ["33cl", "50cl", "1L"],
      "weight": 350,
      "dimensions": { "width": 8, "height": 15, "depth": 8 },
      "color": "brown",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 140,
          "fat": 0,
          "carbohydrates": 39,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [8, 10],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 10,
      "name": "Cristaline 33cl",
      "image": "/bouteille/CRISTALINE_33CL.jpg",
      "link": "/bouteille/cristaline-33cl",
      "price": 0.99,
      "description": "Bouteille d'eau Cristaline, 33cl.",
      "categoryId": 7, // Eau
      "promotion": false,
      "discountPercentage": 0,
      "volume": "33cl",
      "stock": 300,
      "rating": 4.5,
      "reviews": 100,
      "brand": "Cristaline",
      "sku": "CR12345",
      "tags": ["eau", "boisson", "hydratation"],
      "availableSizes": ["33cl", "50cl", "1L"],
      "weight": 350,
      "dimensions": { "width": 8, "height": 15, "depth": 8 },
      "color": "clear",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [9, 11],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 11,
      "name": "Damoiseau 50cl",
      "image": "/bouteille/Damoiseau_50_cl.jpg",
      "link": "/bouteille/damoiseau-50cl",
      "price": 14.99,
      "description": "Bouteille de rhum Damoiseau, 50cl.",
      "categoryId": 3, // Rhum
      "promotion": false,
      "discountPercentage": 0,
      "volume": "50cl",
      "stock": 40,
      "rating": 4.3,
      "reviews": 50,
      "brand": "Damoiseau",
      "sku": "DA5012345",
      "tags": ["rhum", "alcool", "premium"],
      "availableSizes": ["50cl", "70cl"],
      "weight": 500,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "brown",
      "material": "glass",
      "releaseDate": "2023-02-01",
      "expirationDate": "2025-02-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [10, 12],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 12,
      "name": "Damoiseau 5cl",
      "image": "/bouteille/Damoiseau_5cl.jpg",
      "link": "/bouteille/damoiseau-5cl",
      "price": 2.99,
      "description": "Bouteille de rhum Damoiseau, 5cl.",
      "categoryId": 3, // Rhum
      "promotion": false,
      "discountPercentage": 0,
      "volume": "5cl",
      "stock": 100,
      "rating": 4.1,
      "reviews": 30,
      "brand": "Damoiseau",
      "sku": "DA512345",
      "tags": ["rhum", "alcool", "miniature"],
      "availableSizes": ["5cl"],
      "weight": 50,
      "dimensions": { "width": 5, "height": 10, "depth": 5 },
      "color": "brown",
      "material": "glass",
      "releaseDate": "2023-02-01",
      "expirationDate": "2025-02-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [11, 13],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 13,
      "name": "Damoiseau Vieux Cuvée",
      "image": "/bouteille/Damoiseau_Vieux_Cuvee.jpg",
      "link": "/bouteille/damoiseau-vieux-cuvee",
      "price": 29.99,
      "description": "Bouteille de rhum Damoiseau Vieux Cuvée, 70cl.",
      "categoryId": 3, // Rhum
      "promotion": true,
      "discountPercentage": 10,
      "volume": "70cl",
      "stock": 25,
      "rating": 4.6,
      "reviews": 40,
      "brand": "Damoiseau",
      "sku": "DAVC12345",
      "tags": ["rhum", "alcool", "premium"],
      "availableSizes": ["70cl"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "brown",
      "material": "glass",
      "releaseDate": "2023-03-01",
      "expirationDate": "2025-03-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [12, 14],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 14,
      "name": "Damoiseau Vieux 42%",
      "image": "/bouteille/Damoiseau_Vieux_42_jpg",
      "link": "/bouteille/damoiseau-vieux-42",
      "price": 27.99,
      "description": "Bouteille de rhum Damoiseau Vieux 42%, 70cl.",
      "categoryId": 3, // Rhum
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 30,
      "rating": 4.5,
      "reviews": 35,
      "brand": "Damoiseau",
      "sku": "DAV4212345",
      "tags": ["rhum", "alcool", "premium"],
      "availableSizes": ["70cl"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "brown",
      "material": "glass",
      "releaseDate": "2023-03-01",
      "expirationDate": "2025-03-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [13, 15],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 15,
      "name": "Desperados",
      "image": "/bouteille/Desperados.jpg",
      "link": "/bouteille/desperados",
      "price": 2.99,
      "description": "Bouteille de bière Desperados, 33cl.",
      "categoryId": 8, // Bière
      "promotion": false,
      "discountPercentage": 0,
      "volume": "33cl",
      "stock": 150,
      "rating": 4.2,
      "reviews": 70,
      "brand": "Desperados",
      "sku": "DE12345",
      "tags": ["bière", "alcool", "rafraîchissant"],
      "availableSizes": ["33cl", "50cl"],
      "weight": 350,
      "dimensions": { "width": 8, "height": 15, "depth": 8 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 140,
          "fat": 0,
          "carbohydrates": 12,
          "protein": 1
      },
      "allergens": ["gluten"],
      "relatedProducts": [14, 16],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 16,
      "name": "Desperados 6x44cl",
      "image": "/bouteille/Desperados_6x44cl.jpg",
      "link": "/bouteille/desperados-6x44cl",
      "price": 9.99,
      "description": "Pack de 6 bouteilles de bière Desperados, 44cl.",
      "categoryId": 8, // Bière
      "promotion": true,
      "discountPercentage": 15,
      "volume": "6x44cl",
      "stock": 50,
      "rating": 4.4,
      "reviews": 40,
      "brand": "Desperados",
      "sku": "DE64412345",
      "tags": ["bière", "alcool", "pack"],
      "availableSizes": ["6x44cl"],
      "weight": 2000,
      "dimensions": { "width": 20, "height": 30, "depth": 20 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-04-01",
      "expirationDate": "2025-04-01",
      "nutritionFacts": {
          "calories": 140,
          "fat": 0,
          "carbohydrates": 12,
          "protein": 1
      },
      "allergens": ["gluten"],
      "relatedProducts": [15, 17],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 17,
      "name": "Eristoff",
      "image": "/bouteille/Eristoff.jpg",
      "link": "/bouteille/eristoff",
      "price": 14.99,
      "description": "Bouteille de vodka Eristoff, 70cl.",
      "categoryId": 2, // Vodka
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 60,
      "rating": 4.3,
      "reviews": 50,
      "brand": "Eristoff",
      "sku": "ER12345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-05-01",
      "expirationDate": "2025-05-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [16, 18],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 18,
      "name": "Fruisset",
      "image": "/bouteille/fruisset.jpg",
      "link": "/bouteille/fruisset",
      "price": 1.99,
      "description": "Bouteille de boisson fruisée, 33cl.",
      "categoryId": 6, // Boissons gazeuses
      "promotion": false,
      "discountPercentage": 0,
      "volume": "33cl",
      "stock": 200,
      "rating": 4.1,
      "reviews": 60,
      "brand": "Fruisset",
      "sku": "FR12345",
      "tags": ["boisson", "gazeuse", "fruité"],
      "availableSizes": ["33cl", "50cl"],
      "weight": 350,
      "dimensions": { "width": 8, "height": 15, "depth": 8 },
      "color": "clear",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 30,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [17, 19],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 19,
      "name": "Grant's",
      "image": "/bouteille/Grant's.jpg",
      "link": "/bouteille/grants",
      "price": 19.99,
      "description": "Bouteille de whisky Grant's, 70cl.",
      "categoryId": 1, // Whisky
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 40,
      "rating": 4.4,
      "reviews": 55,
      "brand": "Grant's",
      "sku": "GR12345",
      "tags": ["whisky", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-06-01",
      "expirationDate": "2025-06-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [18, 20],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 20,
      "name": "Grey Goose 150cl",
      "image": "/bouteille/grey-goose-magnum-150CL.jpg",
      "link": "/bouteille/grey-goose-150cl",
      "price": 49.99,
      "description": "Bouteille de vodka Grey Goose en format magnum, 1.5L.",
      "categoryId": 2, // Vodka
      "promotion": true,
      "discountPercentage": 10,
      "volume": "1.5L",
      "stock": 20,
      "rating": 4.7,
      "reviews": 40,
      "brand": "Grey Goose",
      "sku": "GG15012345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["1.5L"],
      "weight": 1500,
      "dimensions": { "width": 15, "height": 30, "depth": 15 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-07-01",
      "expirationDate": "2025-07-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [19, 21],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 21,
      "name": "Grey Goose",
      "image": "/bouteille/grey-goose.jpg",
      "link": "/bouteille/grey-goose",
      "price": 29.99,
      "description": "Bouteille de vodka Grey Goose, 70cl.",
      "categoryId": 2, // Vodka
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 50,
      "rating": 4.6,
      "reviews": 60,
      "brand": "Grey Goose",
      "sku": "GG12345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-07-01",
      "expirationDate": "2025-07-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [20, 22],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 22,
      "name": "Heineken",
      "image": "/bouteille/heineken.jpg",
      "link": "/bouteille/heineken",
      "price": 2.99,
      "description": "Bouteille de bière Heineken, 33cl.",
      "categoryId": 8, // Bière
      "promotion": false,
      "discountPercentage": 0,
      "volume": "33cl",
      "stock": 150,
      "rating": 4.5,
      "reviews": 80,
      "brand": "Heineken",
      "sku": "HE12345",
      "tags": ["bière", "alcool", "rafraîchissant"],
      "availableSizes": ["33cl", "50cl"],
      "weight": 350,
      "dimensions": { "width": 8, "height": 15, "depth": 8 },
      "color": "green",
      "material": "glass",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 140,
          "fat": 0,
          "carbohydrates": 12,
          "protein": 1
      },
      "allergens": ["gluten"],
      "relatedProducts": [21, 23],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 23,
      "name": "Jack Daniel's Honey",
      "image": "/bouteille/Jack_Daniels_Honey.jpg",
      "link": "/bouteille/jack-daniels-honey",
      "price": 24.99,
      "description": "Bouteille de whisky Jack Daniel's Honey, 70cl.",
      "categoryId": 1, // Whisky
      "promotion": true,
      "discountPercentage": 15,
      "volume": "70cl",
      "stock": 30,
      "rating": 4.6,
      "reviews": 70,
      "brand": "Jack Daniel's",
      "sku": "JDH12345",
      "tags": ["whisky", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-04-01",
      "expirationDate": "2025-04-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [22, 24],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 24,
      "name": "Jack Daniel's",
      "image": "/bouteille/Jack_Daniels.jpg",
      "link": "/bouteille/jack-daniels",
      "price": 27.99,
      "description": "Bouteille de whisky Jack Daniel's, 70cl.",
      "categoryId": 1, // Whisky
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 50,
      "rating": 4.5,
      "reviews": 120,
      "brand": "Jack Daniel's",
      "sku": "JD12345",
      "tags": ["whisky", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [23, 25],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 25,
      "name": "JB",
      "image": "/bouteille/JB.jpg",
      "link": "/bouteille/jb",
      "price": 19.99,
      "description": "Bouteille de whisky JB, 70cl.",
      "categoryId": 1, // Whisky
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 40,
      "rating": 4.3,
      "reviews": 60,
      "brand": "JB",
      "sku": "JB12345",
      "tags": ["whisky", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-05-01",
      "expirationDate": "2025-05-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [24, 26],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 26,
      "name": "Magnum Ruinart",
      "image": "/bouteille/Magnum_ruinart.jpg",
      "link": "/bouteille/magnum-ruinart",
      "price": 99.99,
      "description": "Bouteille de champagne Ruinart en format magnum, 1.5L.",
      "categoryId": 4, // Champagne
      "promotion": true,
      "discountPercentage": 10,
      "volume": "1.5L",
      "stock": 10,
      "rating": 4.8,
      "reviews": 20,
      "brand": "Ruinart",
      "sku": "MR12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["1.5L"],
      "weight": 1500,
      "dimensions": { "width": 15, "height": 30, "depth": 15 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-06-01",
      "expirationDate": "2025-06-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [25, 27],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 27,
      "name": "Malibu Coco",
      "image": "/bouteille/Malibu_coco.jpg",
      "link": "/bouteille/malibu-coco",
      "price": 14.99,
      "description": "Bouteille de liqueur Malibu Coco, 70cl.",
      "categoryId": 3, // Liqueur
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 50,
      "rating": 4.4,
      "reviews": 70,
      "brand": "Malibu",
      "sku": "MC12345",
      "tags": ["liqueur", "alcool", "coco"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "white",
      "material": "glass",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 180,
          "fat": 10,
          "carbohydrates": 20,
          "protein": 2
      },
      "allergens": ["lactose"],
      "relatedProducts": [26, 28],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 28,
      "name": "Moët & Chandon Rosé",
      "image": "/bouteille/Moet_et_chandon_rose.jpg",
      "link": "/bouteille/moet-chandon-rose",
      "price": 39.99,
      "description": "Bouteille de champagne Moët & Chandon Rosé, 75cl.",
      "categoryId": 4, // Champagne
      "promotion": false,
      "discountPercentage": 0,
      "volume": "75cl",
      "stock": 30,
      "rating": 4.9,
      "reviews": 200,
      "brand": "Moët & Chandon",
      "sku": "MCR12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["75cl", "1.5L"],
      "weight": 800,
      "dimensions": { "width": 12, "height": 30, "depth": 12 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-01-01",
      "expirationDate": "2026-01-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [27, 29],
      "isFeatured": true,
      "isNew": true
  },
  {
      "id": 29,
      "name": "Moët & Chandon Magnum",
      "image": "/bouteille/Moet_et_chandon_Magnum.jpg",
      "link": "/bouteille/moet-chandon-magnum",
      "price": 79.99,
      "description": "Bouteille de champagne Moët & Chandon en format magnum, 1.5L.",
      "categoryId": 4, // Champagne
      "promotion": true,
      "discountPercentage": 10,
      "volume": "1.5L",
      "stock": 15,
      "rating": 4.8,
      "reviews": 150,
      "brand": "Moët & Chandon",
      "sku": "MCM12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["1.5L"],
      "weight": 1500,
      "dimensions": { "width": 15, "height": 30, "depth": 15 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-05-01",
      "expirationDate": "2025-05-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [28, 30],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 30,
      "name": "Nicolas Feuillatte Magnum",
      "image": "/bouteille/Nicolas_feuillatte_Magnum.jpg",
      "link": "/bouteille/nicolas-feuillatte-magnum",
      "price": 69.99,
      "description": "Bouteille de champagne Nicolas Feuillatte en format magnum, 1.5L.",
      "categoryId": 4, // Champagne
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1.5L",
      "stock": 20,
      "rating": 4.7,
      "reviews": 100,
      "brand": "Nicolas Feuillatte",
      "sku": "NFM12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["1.5L"],
      "weight": 1500,
      "dimensions": { "width": 15, "height": 30, "depth": 15 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-06-01",
      "expirationDate": "2025-06-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [29, 31],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 31,
      "name": "Orangeade",
      "image": "/bouteille/orangeade.jpg",
      "link": "/bouteille/orangeade",
      "price": 1.99,
      "description": "Bouteille d'orangeade, 33cl.",
      "categoryId": 6, // Boissons gazeuses
      "promotion": false,
      "discountPercentage": 0,
      "volume": "33cl",
      "stock": 200,
      "rating": 4.1,
      "reviews": 60,
      "brand": "Marque Orangeade",
      "sku": "OR12345",
      "tags": ["boisson", "gazeuse", "orange"],
      "availableSizes": ["33cl", "50cl"],
      "weight": 350,
      "dimensions": { "width": 8, "height": 15, "depth": 8 },
      "color": "orange",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 30,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [30, 32],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 32,
      "name": "Pichet",
      "image": "/bouteille/PICHET.jpg",
      "link": "/bouteille/pichet",
      "price": 4.99,
      "description": "Pichet en plastique, parfait pour les fêtes.",
      "categoryId": 5, // Accessoires
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1L",
      "stock": 100,
      "rating": 4.3,
      "reviews": 50,
      "brand": "Marque Pichet",
      "sku": "PI12345",
      "tags": ["accessoire", "pichet", "fête"],
      "availableSizes": ["1L"],
      "weight": 100,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "clear",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [31, 33],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 33,
      "name": "Poliakov",
      "image": "/bouteille/Poliakov.jpg",
      "link": "/bouteille/poliakov",
      "price": 12.99,
      "description": "Bouteille de vodka Poliakov, 70cl.",
      "categoryId": 2, // Vodka
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 60,
      "rating": 4.2,
      "reviews": 40,
      "brand": "Poliakov",
      "sku": "PO12345",
      "tags": ["vodka", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "clear",
      "material": "glass",
      "releaseDate": "2023-05-01",
      "expirationDate": "2025-05-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [32, 34],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 34,
      "name": "Pomme",
      "image": "/bouteille/pomme.jpg",
      "link": "/bouteille/pomme",
      "price": 0.99,
      "description": "Pomme fraîche, idéale pour les cocktails.",
      "categoryId": 9, // Fruits
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1 unité",
      "stock": 500,
      "rating": 4.5,
      "reviews": 100,
      "brand": "Marque Pomme",
      "sku": "PM12345",
      "tags": ["fruit", "cocktail", "fraîcheur"],
      "availableSizes": ["1 unité"],
      "weight": 200,
      "dimensions": { "width": 8, "height": 8, "depth": 8 },
      "color": "red",
      "material": "fruit",
      "releaseDate": "2023-01-01",
      "expirationDate": "2023-12-31",
      "nutritionFacts": {
          "calories": 50,
          "fat": 0,
          "carbohydrates": 14,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [33, 35],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 35,
      "name": "Red Bull",
      "image": "/bouteille/Red_bull.jpg",
      "link": "/bouteille/red-bull",
      "price": 2.49,
      "description": "Canette de Red Bull, 25cl.",
      "categoryId": 6, // Boissons gazeuses
      "promotion": false,
      "discountPercentage": 0,
      "volume": "25cl",
      "stock": 300,
      "rating": 4.6,
      "reviews": 150,
      "brand": "Red Bull",
      "sku": "RB12345",
      "tags": ["boisson", "énergisante", "rafraîchissant"],
      "availableSizes": ["25cl", "35cl"],
      "weight": 250,
      "dimensions": { "width": 6, "height": 12, "depth": 6 },
      "color": "silver",
      "material": "aluminum",
      "releaseDate": "2023-01-01",
      "expirationDate": "2024-01-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 27,
          "protein": 1
      },
      "allergens": [],
      "relatedProducts": [34, 36],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 36,
      "name": "Ruinart Blanc Magnum",
      "image": "/bouteille/Ruinart_Blanc_Magnum.jpg",
      "link": "/bouteille/ruinart-blanc-magnum",
      "price": 99.99,
      "description": "Bouteille de champagne Ruinart Blanc en format magnum, 1.5L.",
      "categoryId": 4, // Champagne
      "promotion": true,
      "discountPercentage": 10,
      "volume": "1.5L",
      "stock": 10,
      "rating": 4.8,
      "reviews": 20,
      "brand": "Ruinart",
      "sku": "RBM12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["1.5L"],
      "weight": 1500,
      "dimensions": { "width": 15, "height": 30, "depth": 15 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-06-01",
      "expirationDate": "2025-06-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [35, 37],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 37,
      "name": "Ruinart Blanc",
      "image": "/bouteille/Ruinart_Blanc.jpg",
      "link": "/bouteille/ruinart-blanc",
      "price": 49.99,
      "description": "Bouteille de champagne Ruinart Blanc, 75cl.",
      "categoryId": 4, // Champagne
      "promotion": false,
      "discountPercentage": 0,
      "volume": "75cl",
      "stock": 30,
      "rating": 4.7,
      "reviews": 80,
      "brand": "Ruinart",
      "sku": "RB12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["75cl", "1.5L"],
      "weight": 800,
      "dimensions": { "width": 12, "height": 30, "depth": 12 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [36, 38],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 38,
      "name": "Ruinart Rosé",
      "image": "/bouteille/Ruinart_Rose.jpg",
      "link": "/bouteille/ruinart-rose",
      "price": 54.99,
      "description": "Bouteille de champagne Ruinart Rosé, 75cl.",
      "categoryId": 4, // Champagne
      "promotion": false,
      "discountPercentage": 0,
      "volume": "75cl",
      "stock": 25,
      "rating": 4.8,
      "reviews": 70,
      "brand": "Ruinart",
      "sku": "RR12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["75cl", "1.5L"],
      "weight": 800,
      "dimensions": { "width": 12, "height": 30, "depth": 12 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-02-01",
      "expirationDate": "2025-02-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [37, 39],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 39,
      "name": "Saint James",
      "image": "/bouteille/Saint-James.jpg",
      "link": "/bouteille/saint-james",
      "price": 24.99,
      "description": "Bouteille de rhum Saint James, 70cl.",
      "categoryId": 3, // Rhum
      "promotion": false,
      "discountPercentage": 0,
      "volume": "70cl",
      "stock": 40,
      "rating": 4.4,
      "reviews": 60,
      "brand": "Saint James",
      "sku": "SJ12345",
      "tags": ["rhum", "alcool", "premium"],
      "availableSizes": ["70cl", "1L"],
      "weight": 700,
      "dimensions": { "width": 10, "height": 20, "depth": 10 },
      "color": "brown",
      "material": "glass",
      "releaseDate": "2023-03-01",
      "expirationDate": "2025-03-01",
      "nutritionFacts": {
          "calories": 110,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [38, 40],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 40,
      "name": "Cuvée Champagne Grenadine",
      "image": "/bouteille/Cuvee_CHAMPAGNE_GRENADINE.jpg",
      "link": "/bouteille/cuvee-champagne-grenadine",
      "price": 14.99,
      "description": "Bouteille de champagne avec grenadine, 75cl.",
      "categoryId": 4, // Champagne
      "promotion": true,
      "discountPercentage": 15,
      "volume": "75cl",
      "stock": 50,
      "rating": 4.3,
      "reviews": 40,
      "brand": "Marque Champagne",
      "sku": "CG12345",
      "tags": ["champagne", "alcool", "cocktail"],
      "availableSizes": ["75cl"],
      "weight": 800,
      "dimensions": { "width": 12, "height": 30, "depth": 12 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-04-01",
      "expirationDate": "2025-04-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 15,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [39, 41],
      "isFeatured": true,
      "isNew": false
  },
  {
      "id": 41,
      "name": "Cuvée Champagne Canne",
      "image": "/bouteille/Cuvee_CHAMPAGNE_CANNE.jpg",
      "link": "/bouteille/cuvee-champagne-canne",
      "price": 12.99,
      "description": "Bouteille de champagne avec canne, 75cl.",
      "categoryId": 4, // Champagne
      "promotion": false,
      "discountPercentage": 0,
      "volume": "75cl",
      "stock": 45,
      "rating": 4.2,
      "reviews": 35,
      "brand": "Marque Champagne",
      "sku": "CC12345",
      "tags": ["champagne", "alcool", "cocktail"],
      "availableSizes": ["75cl"],
      "weight": 800,
      "dimensions": { "width": 12, "height": 30, "depth": 12 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-05-01",
      "expirationDate": "2025-05-01",
      "nutritionFacts": {
          "calories": 120,
          "fat": 0,
          "carbohydrates": 15,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [40, 42],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 42,
      "name": "TPE",
      "image": "/bouteille/TPE.jpg",
      "link": "/bouteille/tpe",
      "price": 49.99,
      "description": "Terminal de paiement électronique (TPE).",
      "categoryId": 10, // Accessoires
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1 unité",
      "stock": 20,
      "rating": 4.5,
      "reviews": 15,
      "brand": "Marque TPE",
      "sku": "TP12345",
      "tags": ["accessoire", "paiement", "électronique"],
      "availableSizes": ["1 unité"],
      "weight": 500,
      "dimensions": { "width": 15, "height": 10, "depth": 5 },
      "color": "black",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [41, 43],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 43,
      "name": "Vasque",
      "image": "/bouteille/VASQUE.jpg",
      "link": "/bouteille/vasque",
      "price": 9.99,
      "description": "Vasque en plastique, parfaite pour les fêtes.",
      "categoryId": 5, // Accessoires
      "promotion": false,
      "discountPercentage": 0,
      "volume": "1 unité",
      "stock": 100,
      "rating": 4.3,
      "reviews": 50,
      "brand": "Marque Vasque",
      "sku": "VA12345",
      "tags": ["accessoire", "vasque", "fête"],
      "availableSizes": ["1 unité"],
      "weight": 200,
      "dimensions": { "width": 20, "height": 10, "depth": 20 },
      "color": "clear",
      "material": "plastic",
      "releaseDate": "2023-01-01",
      "expirationDate": "2025-01-01",
      "nutritionFacts": {
          "calories": 0,
          "fat": 0,
          "carbohydrates": 0,
          "protein": 0
      },
      "allergens": [],
      "relatedProducts": [42, 44],
      "isFeatured": false,
      "isNew": false
  },
  {
      "id": 44,
      "name": "Veuve Peltier",
      "image": "/bouteille/Veuve_Peltier.jpg",
      "link": "/bouteille/veuve-peltier",
      "price": 29.99,
      "description": "Bouteille de champagne Veuve Peltier, 75cl.",
      "categoryId": 4, // Champagne
      "promotion": false,
      "discountPercentage": 0,
      "volume": "75cl",
      "stock": 30,
      "rating": 4.6,
      "reviews": 60,
      "brand": "Veuve Peltier",
      "sku": "VP12345",
      "tags": ["champagne", "alcool", "luxe"],
      "availableSizes": ["75cl", "1.5L"],
      "weight": 800,
      "dimensions": { "width": 12, "height": 30, "depth": 12 },
      "color": "gold",
      "material": "glass",
      "releaseDate": "2023-06-01",
      "expirationDate": "2025-06-01",
      "nutritionFacts": {
          "calories": 90,
          "fat": 0,
          "carbohydrates": 2,
          "protein": 0
      },
      "allergens": ["sulfites"],
      "relatedProducts": [43, 45],
      "isFeatured": false,
      "isNew": false
  }
]
*/
